### PR TITLE
Saved natural repo

### PR DESCRIPTION
**Pull request by AliAbdulle**
# Description
Created natural field to new class to facility please check if it will display the console.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)  
- [ X] New feature (non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] This change requires a documentation update  

## Testing Instructions
Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

`git checkout master`  
`git fetch --all`  
`git checkout [Aa-TrestlebridgeFarms]`  
`cd src`  
`dotnet run`  
 
When menu show up use option:
1 create facility then
5 Natural facility

Checklist:
- [ ] My code follows the style guidelines of this project  
- [ ] I have performed a self-review of my own code  
- [ ] I have commented my code, particularly in hard-to-understand areas  
- [ ] My changes generate no new warnings or errors  
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by myankura — APPROVED** [review]
I was able to create a natural field. Good job!💯

**Review by rosewisotzky — APPROVED** [review]
YAY GREAT JOB!!!!!!

**Review by MeagMueller — APPROVED** [review]
Wow wow wow!

**Comment by AliAbdulle** [comment]
Merged to master.

**Pull request merged**
